### ISSUE TITLE
Add HTTP proxy support to install windows updates

### ISSUE THREAD

**Issue by DaxterM** [cloudfoundry-incubator/bosh-windows-stemcell-builder#11]
it would be great if Install-WindowsUpdates could take a flag that could allow you to specify http/https proxy to get out to the windows updates servers.

I ran into this in a client environment. As a temporary workaround I added 
netsh winhttp set proxy proxy-server="http=proxy..com:80;https=proxy..com:80" bypass-list="*.noproxu.com"

as the fist command in the install-windowsUpdates function @ https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder/blob/master/bosh-psmodules/modules/BOSH.WindowsUpdates/BOSH.WindowsUpdates.psm1#L41

**Comment by crawsible** [comment]
Hey @DaxterM, I assume you're still using the approach mentioned above? Do you still feel like it's a temporary workaround or has it been easy to maintain?

**Comment by DaxterM** [comment]
@crawsible  it's easy to maintain but requires forking  which makes it difficult to consume updates.  If other clients use this repo to automate the stemcell creation process I imagine they will run into this.

**Comment by crawsible** [comment]
Ah, sorry, I didn't realize this required forking. Seems like a pretty straightforward change; I'll prioritize it.

**Comment by cdelashmutt-pivotal** [comment]
I also need this feature.  Any idea when this might happen?

**Comment by crawsible** [comment]
@cdelashmutt-pivotal We're hoping to get to it within the next two weeks.
