### ISSUE TITLE
link leads to creating a wiki page

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry-incubator/bosh-windows-stemcell-builder#13]
the link in this doc: https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder/blob/master/with-concourse.md

leads to a page that does not exist and if you have edit access on this repo, it leads you to a page to create a new wiki page entry

**Comment by crawsible** [comment]
@sunjayBhatia This looks fixed to me. Can you make sure it works on your end and close this issue if so?

**Comment by sunjayBhatia** [comment]
all fixed
