### ISSUE TITLE
Add support for S3 compatible storage to rake tasks

### ISSUE THREAD

**Issue by DaxterM** [cloudfoundry-incubator/bosh-windows-stemcell-builder#15]
rake build:vsphere_add_updates   and rake build:vsphere  have a hardcoded dependency  to use amazon S3 to push and pull files. Some environments have internal S3 compatible offerings that can be leveraged for this.  I have a fork that supports this and would happy to pair with the team to have it pulled in.

**Comment by crawsible** [comment]
Thank you @DaxterM; as you mentioned to me offline there is at least one other potential user of this behavior as well.

**Comment by datianshi** [comment]
Hey, we are also interested to keep offline with using internal S3 compatible. This pull requests will be very helpful @DaxterM

**Comment by crawsible** [comment]
@DaxterM @datianshi We've pulled this into the backlog and will work on it in ~2 iterations.

**Comment by cdelashmutt-pivotal** [comment]
I need this feature as well.  Any way this could get moved up in priority?

**Comment by crawsible** [comment]
@cdelashmutt-pivotal Dax and I paired on making [a PR for this change](https://www.pivotaltracker.com/story/show/150265521) to the repo on Friday, and it likely will be pulled in sometime this week. I'll report back when it's been merged.

**Comment by davidjahn** [comment]
I've merged the above PR to provide this support!
