### ISSUE TITLE
windows2016 stemcells should turn off realtime malware scanning (and windows2012R2 if possible)

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry-incubator/bosh-windows-stemcell-builder#18]
Leaving on Windows Defender realtime malware scanning introduces a large performance cost for windows2016 vms (especially those running containers during create and delete).

We would like to disable Windows Defender realtime malware scanning to mitigate this.

I'm not sure which part of the `BOSH.CFCell` module is the right place for this but we would like to add:
```
Set-MpPreference -DisableRealtimeMonitoring $true
```
To turn off realtime scanning on the windows2016 stemcell.

I am not sure if the same powershell module is available in the builtin modules for the windows2012R2 stemcell but if it is, it would be great to disable it there as well.

References:
- https://technet.microsoft.com/en-us/itpro/powershell/windows/defender/set-mppreference

**Comment by nathan-alden-inl** [comment]
Great idea! Can't wait for this to be released.
