### ISSUE TITLE
Add support to disable netbios

### ISSUE THREAD

**Issue by DaxterM** [cloudfoundry-incubator/bosh-windows-stemcell-builder#21]
add support to disable netbios TCP/IP to improve security configuration

**Comment by nathan-alden-inl** [comment]
Great idea! Can't wait for this to be released.

Is this being supported in Windows Server 2012 R2 and Windows Server 2016 stemcells?

**Comment by kartiklunkad26** [comment]
Closing as this is available for our Stemcells today.
