### ISSUE TITLE
use vsphere plugin instead of the vmware-vmx plugin

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-incubator/bosh-windows-stemcell-builder#22]
jetbrains created a nice vsphere plugin
https://github.com/jetbrains-infra/packer-builder-vsphere

i think this plugin would be a great addition or maby a replacement for the 'vmware-vmx' plugin
as not everyone have the appropriate licenses for vmware.

what do you think?

**Comment by crawsible** [comment]
@ramonskie Thanks for the suggestion! Currently, our pipelines build vSphere stemcells using VMware Workstation, not vSphere via vCenter, so using this isn't simply a matter of dropping it in. Still, it might be better for us to build in a more similar environment to what we target. We'll schedule an investigation and get back to you.

**Comment by kartiklunkad26** [comment]
@ramonskie Apologies for the late response on this, but we are actually working on moving our stemcell creation process to use vSphere instead of VMWare Workstation. We will provide a tracker story for you to track here!
