### ISSUE TITLE
Does CF support the 2016 Standard (No GUI) install?

### ISSUE THREAD

**Issue by cwb124** [cloudfoundry-incubator/bosh-windows-stemcell-builder#23]
Just curious as we are about to venture into Windows 2016 stemcells.  Any known issue with using the non GUI install of 2016?

**Comment by awmartin** [comment]
Hi there! Luckily we standardize on the non-GUI install, i.e. Windows Server Core. Our instructions may be a bit out of date, but we're going to update them soon once we have our vSphere pipeline running smoothly.

Curiously, are you using cf-deployment to use the new 2016 runtime stack for Cloud Foundry? What's your use case?

**Comment by cwb124** [comment]
We run pivotal currently but looking at OS.  You asking for use case for wanting non gui or for Windows 2016 in general?

**Comment by cwb124** [comment]
Might be a different 'issue' but in trying both gui and no gui versions of 2016, the Install-CFFeatures script fails trying to run the docker service.  I can't manually install the docker service.  

One thing I noticed in the script was this chunk:

`$windowsVersion = (Get-WmiObject -class Win32_OperatingSystem).Caption
  if ($windowsVersion -Match "2012") {
    WindowsFeatureInstall("Web-Webserver")
    WindowsFeatureInstall("Web-WebSockets")
    WindowsFeatureInstall("AS-Web-Support")
    WindowsFeatureInstall("AS-NET-Framework")
    WindowsFeatureInstall("Web-WHC")
    WindowsFeatureInstall("Web-ASP")
  } elseif ($windowsVersion -Match "2016") {
    WindowsFeatureInstall("FS-Resource-Manager")`

I assume that stuff isn't happening for Windows 2016, perhaps that's causing failing?  I haven't dug in a lot, plan to this afternoon.  Wondering if anyone else has seen it.

**Comment by cwb124** [comment]
Wait, can I rem out the docker install parts of that script then and avoid docker entirely?

**Comment by sunjayBhatia** [comment]
@cwb124 yeah, Docker was installed to unblock us (Garden Windows) while we worked on a method of getting a container image onto a VM without Docker. It will be removed soon anyways (and will be removed in the ultimate publicly available stemcells) so you can skip that part of the script if you like

**Comment by cwb124** [comment]
The PS modules in the master branch worked for me on 2016, vs the ones under 1200.4 release.  Different scripts for 2012 vs. 2016 was a nice add.  Good work.
