### ISSUE TITLE
AWS stemcell build should not require specific envvars

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-incubator/bosh-windows-stemcell-builder#26]
The AWS stemcell build task requires environment variables specific to IAM user access and doesn't support alternative forms of AWS authentication, including instance profiles and STS tokens. Rather than expecting a specific authentication method, the AWS task should delegate authentication to the SDK. This may be as simple as replacing

```ruby
    client = S3::Client.new(
      aws_access_key_id: aws_access_key_id,
      aws_secret_access_key: aws_secret_access_key,
      aws_region: aws_region
    )
```

with

```ruby
    client = S3::Client.new
```

cc @wjwoodson

**Comment by xtreme-sameer-vohra** [comment]
Thanks for reporting this @jmcarp, we'll take a look

**Comment by xtreme-sameer-vohra** [comment]
Hi @jmcarp,
You should be able to use instance profiles to authenticate now. Unfortunately, we had trouble getting STS tokens to work.

Thanks for the suggestion.
Sameer
