### ISSUE TITLE
ESXi Compatibility for Windows2016

### ISSUE THREAD

**Issue by jimbasler-pivotal** [cloudfoundry-incubator/bosh-windows-stemcell-builder#27]
We are building a Windows2016 stemcell using vCenter. The directions say to "Select compatibility, ensure that you choose ESXi 6.0 and later" for Windows2016; however, the choice for Windows2016 only appears when we select ESXi 6.5 and use “hardware version 11.” Instructions probably just need to be updated to reflect that.

**Comment by kartiklunkad26** [comment]
@jimbasler-pivotal Hi! Thanks for reporting this. Could you describe this a little further? 

This is what I see currently when I create a new VM. 
![vsphere](https://user-images.githubusercontent.com/14304141/39938274-6766f71c-5520-11e8-8e39-ec0cef4cc963.png)

**Comment by sumkincpp** [comment]
@kartiklunkad26 same notice

[Wiki](https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder/wiki/Creating-a-vSphere-Stemcell-by-Hand) page says that
```
For Windows Server version 1709: Use hardware version 10
For Windows Server 2012 R2: Use hardware version 9
```

Actually, it should be 
```
For Windows Server version 1709: Use hardware version 11 (ESXi 6.0 and later)
For Windows Server 2012 R2: Use hardware version 10 (ESXi 5.5 and later)
```

Windows Server version 1709 appears only after compatibility level (ESXi 6.0 and later), hardware version 11.

**Comment by kartiklunkad26** [comment]
@sumkincpp Thanks! Will incorporate the feedback into the instructions.
