### ISSUE TITLE
Enable Windows long path name support

### ISSUE THREAD

**Issue by jdeppe-pivotal** [cloudfoundry-incubator/bosh-windows-stemcell-builder#28]
I'd like to request the stemcell enable long path name support, thus bumping the max path length from 260 chars to 32KB. (see https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file)

This can easily be done with something like:
```
New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -name LongPathsEnabled -value 1 -force
```

**Comment by kartiklunkad26** [comment]
@jdeppe-pivotal Hi! Could you elaborate on where this causes issue for you or your team? Thank you!

**Comment by jdeppe-pivotal** [comment]
Sure. We're using the stemcell to create Concourse workers. These workers then run a Java build which can end up using path names like `C:\var\vcap\data\houdini-windows\containers\00002b19ael\tmp\build\7e99fb29\built-geode\tmp\junit1354733500719676959\temp\BackupIntegrationTest_809107526backup_Dir\2018-07-26-22-33-50\8e0fb3ef-57b4-4cf9-b34a-760128054051.windows-worker-integration-tests.private.concourse.bosh-4572-loner--0-5e0ebad8\diskstores\diskStore_4d31c6b3a2574728-9bf53d3138d0acac\dir0` (359 chars). In some cases, `.bat` files are launched against these paths which then fail to run.

**Comment by kartiklunkad26** [comment]
@jdeppe-pivotal Sorry for the super late response on this. We are happy to support any PRs for this issue. We can assist you in how to make the PR. You can interrupt @bosh-windows on Cloud Foundry slack in #bosh channel for assistance. Thank you!
