### ISSUE TITLE
Link to download Concourse Worker produces a 404 error

### ISSUE THREAD

**Issue by tonymarkel** [cloudfoundry-incubator/bosh-windows-stemcell-builder#29]
in /bosh-windows-stemcell-builder/wiki/Windows-Worker-and-Concourse-Setup

the link for concourse_windows_amd64.exe should be:

https://concourse-ci.org/download.html

Thanks,

-- 
Tony Markel

**Comment by aminjam** [comment]
Thanks @tonymarkel. This is updated.
