### ISSUE TITLE
Windows 2019 stemcell could only be created using a vmdk set to use BIOS

### ISSUE THREAD

**Issue by arjun024** [cloudfoundry-incubator/bosh-windows-stemcell-builder#32]
Using: VMWare Workstation
Context: Step 1

When the VM was created with firmware type set to UEFI (which is the default option if you follow along the create-a-vm process on VMWare Workstation), the final stemcell would not boot. It hung on "Operating system not found".

When the same process was repeated with firmware type set to BIOS, a bootable stemcell was successfully created. It would be good idea to add this in the wiki!

**Comment by kartiklunkad26** [comment]
@arjun024 Thanks for creating this issue. We currently are working on supporting Windows 2019, and will update our instructions accordingly to ensure you can use the right set of instructions !

**Comment by benmoss** [comment]
Fixed in https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder/wiki/Creating-a-vSphere-Windows-Stemcell/_compare/0afc0171c4b9abcf886546d1dcf6eb7370a55c18...78a65dd117a38af01224ca451f51d2847b6a0dc6
