### ISSUE TITLE
Http/s proxy issues

### ISSUE THREAD

**Issue by RedOnePrime** [cloudfoundry-incubator/bosh-windows-stemcell-builder#37]
Two issues:

<b>Issue One:</b>

Can quotes be added (my preference) or require all three varaibles? Currently, when the variables expand in ruby they are used in powershell without quoting so if you don't specify one then the params shift position when passed to the Set-ProxySettings function since it avoids spaces

https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder/blob/7cf67af6c927b3b43db631e414a4faf412377153/lib/packer/config/provisioners.rb#L18

<h4><b>Current:</b></h4>
<code>"Set-ProxySettings #{http_proxy} #{https_proxy} #{bypass_list}" </code> <br>
<b>Variable values</b>
<ul><li>http_proxy: "111.222.333.444"</li>
<li>https_proxy: ""</li>

<li>bypass_list: "some.domain;anotherdomain"</li>
</ul>
<b>Expands to:</b>
<i>Set-ProxySettings 111.222.333.444 some.domain;anotherdomain </i>

<br><br>
<h4><b>Expected code:</b></h4>
<code>"Set-ProxySettings \"#{http_proxy}\" \"#{https_proxy}\" \"#{bypass_list}\""</code> <br>
<b>Variable values</b>:
<ul><li>http_proxy: "111.222.333.444"</li>
<li>https_proxy: ""</li>
<li>bypass_list: "some.domain;anotherdomain"</li>
</ul>

<b>Expands to:</b>
<i>Set-ProxySettings "111.222.333.444" "" "some.domain;anotherdomain"</i>

<b>Issue Two:</b>
Invoke-WebRequest, which is used in the BOSH utils, does not seem to respect or use the proxy settings from netsh winhttp without explicitly using the -Proxy param. This might be due to the default powershell version on the VM being built (windows2012 in this case) and could behave differently in newer windows server version. Can the -Proxy param be used if proxy settings are specified?

To compensate for this I had to make a hack-type of change to the packer provisioning. I used the powershell/.net WebProxy every time the server was rebooted/restarted prior to executing any additional provisioning steps. The challenge is that now the ruby code has been updated in this Github to no longer specify the list/array of provisioners in provisioners.rb. Instead, it is now relying on the ERB template so my override needs to be done and maintained differently. Prior to these changes I had a fully operational stemcell provision/build process using vSphere, the jetbrains packer plugin, and concourse + custom ruby based off work done by Stark and Wayne. Essentially I continued on from https://www.pivotaltracker.com/n/projects/1479998/stories/154538547 and got it working.

Here is the example of my provisioning step.
<code>
      def self.powershell_webproxy_restart_provisioner(command, timeout="1h")
        {
          'type' => 'windows-restart',
          'restart_command' => "powershell.exe -Command [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;[system.net.webrequest]::defaultwebproxy = new-object system.net.webproxy(Get-Content c:\\provision\\proxyaddress);#{command}",
          'restart_timeout' => "#{timeout}"
        }
      end
</code>

There was no easy way to set this value in ruby without hard-coding it since the provisioning vvalues in provisioners.rb didn't take any params from the calling code. So instead of modifying all of that every time it was needed, I made a copy of the existing function and modified it to the above.

The final step, as you could guess, was to have a custom provisioning step at the start to copy the <i>proxyaddress</i> file to c:\provision. That way it could be referenced across reboots until provisioning was complete. This is just one solution I came up with that could work and was verifiable on the cell during testing but might not be ideal.

Last notes:  
<ul>
<li>When using either the -Proxy param or the WebProxy object for Invoke-WebRequest, credentials could be needed (not needed in our case). </li>
<li>Also, ensuring proper masking of those credentials in any stdout that ruby/powershell emit.</li>
<li>The bummer is that right after getting this all to work (in early October), the strategy this repo is using has changed drastically so I have to do a lot of this over again and figure out how to inject these changes. However if the proxy issues can be fixed then it is only extensibility that has been lost and I can use the updated ruby unedited without my mods to provisioners.rb. I think it would be more appropriate to tackle the extensibility discussion as it relates to this item in another post/comment, so I'll do that.</li>
</ul>

Thanks,

-Red

**Comment by RedOnePrime** [comment]
So the trick is that it must be escaped in ruby so that it outputs to escaped json to be read by packer and just have the quotes left.

Here is the updated line of code that works
<code>@proxy_settings = http_proxy ? "\\\"#{http_proxy}\\\" \\\"#{https_proxy}\\\" \\\"#{bypass_list}\\\"" : ''@proxy_settings = http_proxy ? "\\\"#{http_proxy}\\\" \\\"#{https_proxy}\\\" \\\"#{bypass_list}\\\"" : ''</code>

**Comment by xtreme-gabelan-satchithanantham** [comment]
Hey @RedOnePrime, 

Thanks for the detailed notes on these issues and sorry for the delay in response. 

Regarding Issue 1: This seems to be a straight forward bug and we'll ensure that `https_proxy` can be empty with values for the other parameters. You can track the bug progress here: https://www.pivotaltracker.com/story/show/162209414

Issue 2: I've got a couple of clarifying questions regarding this one. 
- I can't find an `Invoke-Webrequest` call under BOSH.utils. The only `Invoke-Webrequest`s I found under the bosh-psmodules are in the install windows updates task where we explicitly apply a few updates that don't get picked up by the update installer. We typically expect users to start with a machine that's up to date when building stemcells but I understand you have your stemcell creation process automated using Packer. I'm wondering if you're using the PS functions to install windows updates as well?
- What powershell version are you using for your windows2012 stemcells?  We now ensure our public stemcells use PS 5.1 as PS 4 was giving us issues with symlinks. 

Thanks

**Comment by kartiklunkad26** [comment]
@RedOnePrime Looking for your feedback on this issue!

**Comment by RedOnePrime** [comment]
Sorry I did not get, or missed, the notification that someone relied.

Invoke-WebRequest always runs to download and run that patch regardless of the stemcell being up to date because the litmus test is if c:\provision\patch.msu exists; which is never the case because New-Provisioner and Clear-Provisioner steps modify that directory.

The powershell version is up to date on the stemcell. When I posted this issue it was prior to the change in this repo to use ERB so while the issue still existed post-change it might be a slightly different fix.

The overall issue is with proxy. As it relates to direct downloads (as noted in my original post) or with windows updates. The kicker on the windows updates side of things, is that it seems to be a 50/50 whether BITS will succeed with the downloads. The method the ps-modules uses to download these updates looks to be the recommended process (which involves BITS under the hood), however the Microsoft.Update.Session com object does not give feedback if it has successfully downloaded the updates. Here is some output when it silently fails:


1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:05:05.6063476-05:00 Checking For Windows Updates
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:05:05.6375963-05:00 Script: C:\Program Files\WindowsPowerShell\Modules\BOSH.WindowsUpdates\BOSH.WindowsUpdates.psm1
1548688350,,ui,message,    vsphere-clone: Script User: WIN-server\Provisioner
1548688350,,ui,message,    vsphere-clone: Started: 1/28/2019 10:05:05 AM
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.2325148-05:00 There are 2 more updates.
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.2481295-05:00 Update for Windows Server 2012 R2 (KB3118401)
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.2637528-05:00 Install this update to resolve issues in Windows. For a complete listing of the issues that are included in this update%!(PACKER_COMMA) see the associated Microsoft Knowledge Base article for more information. After you install this item%!(PACKER_COMMA) you may have to restart your computer.
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.2793756-05:00 False
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.2793756-05:00 True
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.2950010-05:00 Update for Windows Server 2012 R2 (KB3162835)
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.2950010-05:00 Install this update to resolve issues in Windows. For a complete listing of the issues that are included in this update%!(PACKER_COMMA) see the associated Microsoft Knowledge Base article for more information. After you install this item%!(PACKER_COMMA) you may have to restart your computer.
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.2950010-05:00 False
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.2950010-05:00 True
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.3731263-05:00 Evaluating Available Updates with limit of 500:
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.4200046-05:00 Adding: Update for Windows Server 2012 R2 (KB3118401)
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.4356266-05:00 Adding: Update for Windows Server 2012 R2 (KB3162835)
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:10:59.4356266-05:00 Downloading Updates...
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:11:24.5294268-05:00 The following updates are downloaded and ready to be installed:
1548688350,,ui,message,    vsphere-clone: 2019-01-28T10:11:24.5450535-05:00 No updates available to install...


You can see at the end that it adds 2 updates and says it is downloading them, but none are in the resultant collection. This means the catch block is not catching something, or the download is not throwing in all scenarios when it (arguably) should; I think the latter.

-Red

**Comment by jfeeny** [comment]
Hi, @RedOnePrime, sorry for the delay here.

We've created a tracker story for your issue https://www.pivotaltracker.com/story/show/162209414 so you can follow its progress.

**Comment by kartiklunkad26** [comment]
@RedOnePrime We believe we have provided a resolution for this request. Please feel free to re-open the issue if it hasn't resolved your issue.
