### ISSUE TITLE
Description text contains broken links

### ISSUE THREAD

**Issue by trondhindenes** [cloudfoundry-incubator/bosh-windows-stemcell-builder#4]
Broken links in:
`This repo contains a set of scripts for automating the process of building BOSH Windows Stemcells. A [Concourse](http://concourse.ci/) [pipeline](https://github.com/cloudfoundry-incubator/greenhouse-ci/blob/master/bosh-windows-stemcells.yml) for the supported platforms (AWS, vSphere) can be found [here](https://main.bosh-ci.cf-app.com/pipelines/windows-stemcells).`

404:
https://github.com/cloudfoundry-incubator/greenhouse-ci/blob/master/bosh-windows-stemcells.yml
not found?
https://main.bosh-ci.cf-app.com/pipelines/windows-stemcells

It's still very unclear to me how to create a windows stemcell on aws based on the documentation i've found.

**Comment by awmartin** [comment]
@trondhindenes Thanks for this. We are working to update this repo with new processes for building stemcells and will update the text.

For the latest vSphere instructions, please [see this page](https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder/blob/master/create-manual-vsphere-stemcells.md). This is the simplest way to do this.

While a similar process may be used for AWS, GCP, or Azure, we will be releasing pre-built stemcells and corresponding light stemcells, targeted for early April, so you won't have to build them yourself.

**Comment by trondhindenes** [comment]
thanks - I understand that there's a lot of things happening with windows-stemcells atm - I'll be patient :-)

**Comment by sunjayBhatia** [comment]
The README has changed quite a bit and there are updated instructions/links. We cannot link to our pipelines as the BOSH team has restricted access to them. Public IAAS stemcells will be on bosh.io soon (unfortunately we do not have a date yet). Closing this out as we would like to get feedback on our updated documentation.
